CREATE DATABASE intranetvm;

CREATE TABLE usuarios(

	id INTEGER NOT  NULL AUTO_INCREMENT,
	
	login VARCHAR(60) UNIQUE KEY NOT NULL,
	senha VARCHAR(60) NOT NULL,
	nivel_acesso VARCHAR(1) NOT NULL,
   

	CONSTRAINT pk_usuarios PRIMARY KEY (id)
);